app:
  name: "college"
  mode: "dev"
  port: 8081


log:
  level: "debug"
  filename: "college.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: 152.136.50.60
  port: 3306
  user: "root"
  password: "zyf9630"
  db: "college"
  max_open_connection: 20
  max_idle_connection: 10

redis:
  host: 152.136.50.60
  port: 6378
  password: "seatMarch"
  db: 1
  pool_size: 100

